<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <PropertyGroup Condition="$(OS) == 'Unix' OR $(OS) == 'OSX'">
    <VALHEIM_INSTALL Condition="'$(VALHEIM_INSTALL)' == ''">$(HOME)/Library/Application Support/Steam/steamapps/common/Valheim</VALHEIM_INSTALL>
    <VALHEIM_MANAGED>$(VALHEIM_INSTALL)/Valheim.app/Contents/Resources/Data/Managed</VALHEIM_MANAGED>
    <BEPINEX_PATH>$(VALHEIM_INSTALL)/BepInEx</BEPINEX_PATH>
    <BEPINEX_CORE>$(BEPINEX_PATH)/core</BEPINEX_CORE>
    <BEPINEX_PLUGINS>$(BEPINEX_PATH)/plugins</BEPINEX_PLUGINS>
    <PUBLICIZED_PATH>$(VALHEIM_MANAGED)/publicized_assemblies</PUBLICIZED_PATH>
  </PropertyGroup>

  <PropertyGroup Condition="$(OS) == 'Windows_NT'">
    <VALHEIM_INSTALL Condition="'$(VALHEIM_INSTALL)' == ''">C:\Program Files (x86)\Steam\steamapps\common\Valheim</VALHEIM_INSTALL>
    <VALHEIM_MANAGED>$(VALHEIM_INSTALL)\valheim_Data\Managed</VALHEIM_MANAGED>
    <BEPINEX_PATH>$(VALHEIM_INSTALL)\BepInEx</BEPINEX_PATH>
    <BEPINEX_CORE>$(BEPINEX_PATH)\core</BEPINEX_CORE>
    <BEPINEX_PLUGINS>$(BEPINEX_PATH)\plugins</BEPINEX_PLUGINS>
    <PUBLICIZED_PATH>$(VALHEIM_MANAGED)\publicized_assemblies</PUBLICIZED_PATH>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="BepInEx">
      <HintPath>$(BEPINEX_CORE)/BepInEx.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(BEPINEX_CORE)/0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Jotunn">
      <HintPath>$(BEPINEX_CORE)/Jotunn.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="UnityEngine">
      <HintPath>$(VALHEIM_MANAGED)/UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(VALHEIM_MANAGED)/UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.AssetBundleModule">
      <HintPath>$(VALHEIM_MANAGED)/UnityEngine.AssetBundleModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>$(VALHEIM_MANAGED)/UnityEngine.IMGUIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>$(VALHEIM_MANAGED)/UnityEngine.PhysicsModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="assembly_valheim">
      <HintPath>$(PUBLICIZED_PATH)/assembly_valheim_publicized.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="assembly_guiutils">
      <HintPath>$(PUBLICIZED_PATH)/assembly_guiutils_publicized.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="assembly_utils">
      <HintPath>$(PUBLICIZED_PATH)/assembly_utils_publicized.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="SoftReferenceableAssets">
      <HintPath>$(PUBLICIZED_PATH)/SoftReferenceableAssets_publicized.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
